spring:
  application:
    name: response-server

  activemq:
    broker-url: tcp://localhost:61616  # default
    user: admin                        # default
    password: admin                    # default

server:
  port: 8882

message:
  topic: dongyeop

kafka:
  url: localhost:9092
  group-id: group_1

activemq:
  queue:
    name: sample-queue