spring:
  application:
    name: response-server

  activemq:
    broker-url: tcp://localhost:61616  # default
    user: admin                        # default
    password: admin                    # default

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8882

message:
  topic: dongyeop

kafka:
  url: localhost:9092
  group-id: group_1

activemq:
  queue:
    name: sample-queue

rabbitmq:
  queue:
    name: sample.queue
  exchange:
    name: sample.exchange
  routing:
    key: sample.key